version: 1

redis:
  image: redis

db:
  image: postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123

vote:
  image: example-voting-app-vote
  ports:
    - 5000:80
  links:
    - redis

result:
  image: example-voting-app-result
  ports:
    - 5001:80
  links:
    - db

worker:
  image: example-voting-app-worker
  links:
    - redis
    - db
