services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  vote:
    build: ./example-voting-app/vote
    ports:
      - 5000:80
    links:
      - redis

  result:
    build: ./example-voting-app/result
    ports:
      - 5001:80
    links:
      - db

  worker:
    build: ./example-voting-app/worker
    links:
      - redis
      - db
